---
openapi: 3.0.2
info:
  title: 595ASE
  version: 1.0.0
  description: API for 595 ASE experimental tool
paths:
  /:
    summary: Connection check
    get:
      responses:
        "200":
          content:
            application/json: {}
          description: Connection OK
      operationId: helloWorld
      summary: Hello world
  /log:
    summary: To log datapoints
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataLog'
        required: true
      responses:
        "200":
          description: Datapoint received
        "400":
          content:
            application/json:
              schema:
                type: string
              examples:
                Bad Request:
                  value: Datapoint malformed!
          description: Datapoint malformed
        "500":
          description: Internal server error
      operationId: logData
      summary: Receive logged datapoint from frontend
components:
  schemas:
    DataLog:
      title: Root Type for Datapoint
      description: A data log from the frontend
      required:
      - timestamp
      type: object
      properties:
        participantID:
          description: Randomly generated unique ID for study participant
          type: string
        timestamp:
          description: Timestamp of data log
          type: string
        payloads:
          description: Contains captured data
          type: array
          items:
            $ref: '#/components/schemas/Payload'
          properties:
            context:
              type: string
            data:
              type: object
              properties:
                familiarity:
                  format: double
                  type: number
                experience:
                  format: double
                  type: number
                skill:
                  format: double
                  type: number
      example:
        participantID: some text
        payloads:
        - context: some text
          datapoint: {}
        timestamp: some text
    DatapointStartup:
      description: Data from experiment startup
      required:
      - familiarity
      - skill
      - lastWorked
      - unique
      - longAgo
      - languages
      type: object
      properties:
        familiarity:
          description: Value 0-1 representing participant's familiarity with Regexes
          type: number
        skill:
          description: Value 0-1 representing participant's skill with Regexes
          type: number
        lastWorked:
          description: When participant last worked with regular expressions
          type: string
        unique:
          description: How many unique regular expressions participant has worked
            with
          type: string
        longAgo:
          description: How long ago participant first encounter regular expressions
          type: string
        languages:
          description: Programming languages in which participant has worked with
            regular expressions
          type: array
          items:
            type: string
      example:
        familiarity: 0.4
        skill: 0.7
        lastWorked: some text
        unique: some text
        longAgo: some text
        languages:
        - some text
        - some text
    DatapointChallenge:
      description: Data collected from one of the "challenge" stages of the experiment.
      required:
      - timeToComplete
      - numAttempts
      - numChecks
      - correct
      type: object
      properties:
        timeToComplete:
          description: Time taken to complete the challenge overall (in milliseconds)
          type: integer
        numAttempts:
          description: Number of answer submission attempts
          type: integer
        numChecks:
          description: Number of times participant utilized the comprehension method
            to check their answer
          type: integer
        correct:
          description: Whether participant got the question correct or not (default
            false)
          type: boolean
      example:
        timeToComplete: 33
        numAttempts: 90
        numChecks: 59
        correct: true
    Payload:
      description: 'Contains captured experimental data '
      required:
      - context
      - datapoint
      type: object
      properties:
        context:
          description: |
            Context data is from.  Used to identify which part of the experiment the data is from and how to parse it properly on the backend.

            Possible values include:
                "startup",
                "control",
                "explain",
                "automata",
                "code",
                "conclusion"
          type: string
        datapoint:
          $ref: '#/components/schemas/Datapoint'
          description: Results from this stage of the experiment
      example:
        context: some text
        datapoint: {}
    Datapoint:
      oneOf:
      - $ref: '#/components/schemas/DatapointChallenge'
      - $ref: '#/components/schemas/DatapointStartup'
      description: A datapoint
      type: object
